let startCoords = { lat: 0, lon: 0 }; let endCoords = { lat: 0, lon: 0 }; let debounceTimer = null; window.currentFlotta = []; let costChartInstance = null;

const socket = (typeof io !== 'undefined') ? io('http://localhost:3000') : null;
if (socket) {
  socket.on('adat_frissites', () => {
    if (window.AppState.token) {
      loadAutok(); loadUtak();
      if (window.AppState.user.role === 'ADMIN') { loadAktivFlotta(); renderDashboard(); loadAuditLog(); }
    }
  });
}

function resetDistanceField(resetStart = true, resetEnd = true) { if (resetStart) startCoords = { lat: 0, lon: 0 }; if (resetEnd) endCoords = { lat: 0, lon: 0 }; const tavInput = document.getElementById('utTav'); if (tavInput) { tavInput.value = ''; tavInput.classList.remove('border-emerald-500'); } }
function calculateDistance(lat1, lon1, lat2, lon2) { const R = 6371; const dLat = (lat2 - lat1) * Math.PI / 180; const dLon = (lon2 - lon1) * Math.PI / 180; const a = Math.sin(dLat / 2) * Math.sin(dLat / 2) + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) * Math.sin(dLon / 2); return (R * (2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)))).toFixed(1); }
function searchOSM(inputEl, dropdownId) { clearTimeout(debounceTimer); if (inputEl.id === 'utIndulas') resetDistanceField(true, false); if (inputEl.id === 'utErkezes') resetDistanceField(false, true); const query = inputEl.value.trim(); const dropdown = document.getElementById(dropdownId); if (query.length < 3) return dropdown.classList.add('hidden'); debounceTimer = setTimeout(async () => { try { const res = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(query)}&limit=5&accept-language=hu`); const results = await res.json(); if (results.length === 0) { dropdown.innerHTML = `<div class="p-3 text-xs text-slate-400 text-center">Nincs találat</div>`; return dropdown.classList.remove('hidden'); } dropdown.innerHTML = results.map(item => `<div onclick="selectLocation('${inputEl.id}', '${dropdownId}', '${item.display_name.split(',').slice(0,3).join(', ').trim().replace(/'/g, "\\'")}', ${item.lat}, ${item.lon})" class="p-3 hover:bg-slate-700 cursor-pointer flex gap-2"><span class="text-blue-400">📍</span><div><div class="text-xs font-semibold text-white">${item.display_name.split(',').slice(0,3).join(', ').trim()}</div></div></div>`).join(''); dropdown.classList.remove('hidden'); } catch (err) {} }, 800); }
function selectLocation(inputId, dropdownId, locationName, lat, lon) { document.getElementById(inputId).value = locationName; document.getElementById(dropdownId).classList.add('hidden'); if (inputId === 'utIndulas') startCoords = { lat, lon }; if (inputId === 'utErkezes') endCoords = { lat, lon }; if (startCoords.lat !== 0 && endCoords.lat !== 0) { const tavInput = document.getElementById('utTav'); tavInput.value = calculateDistance(startCoords.lat, startCoords.lon, endCoords.lat, endCoords.lon); tavInput.classList.add('border-emerald-500'); } }

function openEditModal(rendszam) { const auto = window.currentFlotta.find(a => a.rendszam === rendszam); if(!auto) return; document.getElementById('editAutoModal').classList.remove('hidden'); document.getElementById('editRendszam').value = auto.rendszam; document.getElementById('editTipus').value = auto.tipus; document.getElementById('editStatusz').value = auto.statusz; document.getElementById('editItp').value = auto.itp ? auto.itp.split('T')[0] : ''; document.getElementById('editRca').value = auto.rca ? auto.rca.split('T')[0] : ''; document.getElementById('editRovinieta').value = auto.rovinieta ? auto.rovinieta.split('T')[0] : ''; }
function closeEditModal() { document.getElementById('editAutoModal').classList.add('hidden'); }
async function openSzervizModal(rendszam) { document.getElementById('szervizModal').classList.remove('hidden'); document.getElementById('szervizModalTitle').textContent = `🛠️ ${rendszam} Szerviz`; document.getElementById('szervizAutoRendszam').value = rendszam; const lista = document.getElementById('szervizLista'); lista.innerHTML = '<div class="text-center text-slate-400 py-4">Betöltés...</div>'; try { const szervizek = await API.fetchSzerviz(window.AppState.token, rendszam); if(szervizek.length === 0) { lista.innerHTML = '<div class="text-center text-slate-500 text-sm py-4">Nincs rögzített szerviz.</div>'; } else { lista.innerHTML = szervizek.map(sz => `<div class="bg-slate-900 p-3 rounded mb-2 border border-slate-700"><div class="flex justify-between items-center mb-1"><span class="font-bold text-blue-400 text-sm">${sz.datum.split('T')[0]}</span><span class="text-xs bg-slate-800 px-2 py-0.5 rounded text-slate-300 border border-slate-600">${sz.kilometer} km</span></div><div class="text-sm text-slate-200">${sz.leiras}</div></div>`).join(''); } } catch(e) { lista.innerHTML = '<div class="text-red-400 text-sm py-4">Hiba.</div>'; } }
function closeSzervizModal() { document.getElementById('szervizModal').classList.add('hidden'); }
function openLezarModal(id, rendszam) { document.getElementById('lezarModal').classList.remove('hidden'); document.getElementById('lezarUtId').value = id; document.getElementById('lezarModalTitle').textContent = `⛽ Fuvar Lezárása: #${id} (${rendszam})`; }
function closeLezarModal() { document.getElementById('lezarModal').classList.add('hidden'); }

async function renderDashboard() {
  const token = window.AppState.token; if (!token || typeof Chart === 'undefined') return;
  const ctx = document.getElementById('costChart'); if (!ctx) return;
  try {
    const utak = await API.fetchUtak(token, true, '');
    if (!Array.isArray(utak)) return;
    const haviKoltsegek = {};
    utak.forEach(u => { if (u.status === 'TELJESITVE') { haviKoltsegek[u.honap_ev] = (haviKoltsegek[u.honap_ev] || 0) + u.koltseg; } });
    const labels = Object.keys(haviKoltsegek).sort(); const data = labels.map(l => haviKoltsegek[l]);
    if (costChartInstance) { costChartInstance.data.labels = labels; costChartInstance.data.datasets[0].data = data; costChartInstance.update(); } 
    else { costChartInstance = new Chart(ctx, { type: 'bar', data: { labels: labels, datasets: [{ label: 'Üzemanyag Költség (RON)', data: data, backgroundColor: 'rgba(59, 130, 246, 0.5)', borderColor: '#3b82f6', borderWidth: 1, borderRadius: 4 }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { labels: { color: '#cbd5e1' } } }, scales: { y: { beginAtZero: true, grid: { color: 'rgba(51, 65, 85, 0.5)' }, ticks: { color: '#94a3b8' } }, x: { grid: { color: 'rgba(51, 65, 85, 0.5)' }, ticks: { color: '#94a3b8' } } } } }); }
  } catch(e) {}
}

async function loadAuditLog() {
  const token = window.AppState.token; if (!token || window.AppState.user.role !== 'ADMIN') return;
  const container = document.getElementById('auditLogList');
  try {
    const logs = await API.fetchAudit(token);
    container.innerHTML = logs.map(l => `<tr><td class="py-2 text-slate-500">${new Date(l.datum).toLocaleString()}</td><td class="py-2 font-bold">${l.felhasznalo}</td><td class="py-2 text-blue-400">${l.muvelet}</td><td class="py-2">${l.reszletek}</td></tr>`).join('');
  } catch(e) {}
}

async function renderUI() {
  const token = window.AppState.token; const currentUser = window.AppState.user;
  if (!token) { document.getElementById('loginSection').classList.remove('hidden'); document.getElementById('adminSection').classList.add('hidden'); document.getElementById('kliensSection').classList.add('hidden'); document.getElementById('userInfo').classList.add('hidden'); return; }
  
  document.getElementById('loginSection').classList.add('hidden'); document.getElementById('userInfo').classList.remove('hidden'); document.getElementById('welcomeText').textContent = `Üdv, ${currentUser.username}!`; document.getElementById('roleBadge').textContent = currentUser.role;
  const soforUrlap = document.getElementById('soforUrlapContainer'); const alertContainer = document.getElementById('alertContainer'); if(alertContainer) alertContainer.innerHTML = '';
  const szuro = document.getElementById('kerelmekSzuro'); if(szuro && !szuro.value) { const ma = new Date(); szuro.value = `${ma.getFullYear()}-${String(ma.getMonth() + 1).padStart(2, '0')}`; }

  if (currentUser.role === 'ADMIN') {
    document.getElementById('adminSection').classList.remove('hidden'); document.getElementById('kliensHeader').classList.add('hidden'); if (soforUrlap) soforUrlap.classList.add('hidden');
    try { 
      const riasztasok = await API.fetchAlerts(token); 
      if(Array.isArray(riasztasok) && riasztasok.length > 0 && alertContainer) { 
        alertContainer.innerHTML = riasztasok.map(r => {
          const isWarning = r.includes('⚠️');
          const bgColor = isWarning ? 'bg-amber-900/50' : 'bg-red-900/50';
          const borderColor = isWarning ? 'border-amber-500' : 'border-red-500';
          const textColor = isWarning ? 'text-amber-200' : 'text-red-200';
          return `<div class="${bgColor} border-l-4 ${borderColor} p-4 rounded ${textColor} text-sm font-semibold mb-3 flex items-center shadow-lg"><span class="mr-3 text-xl">${isWarning ? '⚠️' : '🚨'}</span> ${r.replace('⚠️ ', '').replace('🚨 ', '')}</div>`;
        }).join(''); 
      } 
    } catch (e) { }
    loadAktivFlotta(); renderDashboard(); loadAuditLog();
  } else { document.getElementById('adminSection').classList.add('hidden'); document.getElementById('kliensHeader').classList.remove('hidden'); if (soforUrlap) soforUrlap.classList.remove('hidden'); }
  
  document.getElementById('kliensSection').classList.remove('hidden'); resetDistanceField(true, true); const datumInput = document.getElementById('utDatum'); if (datumInput && !datumInput.value) datumInput.value = new Date().toISOString().split('T')[0];
  loadAutok(); loadUtak(); 
}

function formatDateStr(isoStr) { return isoStr ? isoStr.split('T')[0] : 'Nincs'; }
async function loadAktivFlotta() { const token = window.AppState.token; const currentUser = window.AppState.user; if (!token || currentUser.role !== 'ADMIN') return; const container = document.getElementById('aktivFlottaList'); if(!container) return; try { const aktivUtak = await API.fetchAktivFlotta(token); if (!Array.isArray(aktivUtak) || aktivUtak.length === 0) { container.innerHTML = '<div class="text-sm text-slate-400 py-2">Jelenleg nincs kint a flotta egyetlen autója sem.</div>'; return; } container.innerHTML = aktivUtak.map(u => `<div class="bg-slate-900 p-3 rounded mb-2 border border-blue-900/50 flex justify-between items-center"><div><div class="font-bold text-white text-sm flex items-center gap-2">🚘 ${u.auto_rendszam} <span class="text-[9px] bg-blue-900/80 text-blue-300 px-1.5 py-0.5 rounded tracking-widest uppercase">Úton</span></div><div class="text-xs text-slate-400 mt-1">Sofőr: <span class="text-blue-400 font-semibold">${u.sofor_nev}</span></div></div><div class="text-right"><div class="text-xs text-slate-300">${u.indulas} <span class="text-blue-500">➔</span> ${u.erkezes}</div></div></div>`).join(''); } catch(e) {} }
async function loadAutok() { const token = window.AppState.token; const currentUser = window.AppState.user; if (!token) return; const datumInput = document.getElementById('utDatum'); const formDate = datumInput ? datumInput.value : new Date().toISOString().split('T')[0]; try { const autok = await API.fetchAutok(token, formDate); if (!Array.isArray(autok)) return; window.currentFlotta = autok; document.getElementById('autoList').innerHTML = autok.map(a => `<div class="bg-slate-900 p-4 rounded-lg border ${a.statusz === 'FOGLALT' ? 'border-red-900/50' : 'border-slate-700'} flex flex-col justify-between"><div><div class="flex justify-between items-start mb-3"><div><div class="font-bold text-white text-lg">${a.rendszam}</div><div class="text-xs text-slate-400">${a.tipus}</div></div><span class="text-xs px-2 py-1 rounded font-bold ${a.statusz === 'ELERHETO' ? 'bg-emerald-900/40 text-emerald-400' : 'bg-red-900/40 text-red-400'}">${a.statusz}</span></div><div class="text-[10px] text-slate-400 grid grid-cols-3 gap-1 bg-slate-950 p-2 rounded text-center"><div><span class="block text-slate-500">ITP</span> ${formatDateStr(a.itp)}</div><div><span class="block text-slate-500">RCA</span> ${formatDateStr(a.rca)}</div><div><span class="block text-slate-500">Rovinieta</span> ${formatDateStr(a.rovinieta)}</div></div></div>${currentUser && currentUser.role === 'ADMIN' ? `<div class="mt-3 flex gap-1 border-t border-slate-800 pt-3"><button onclick="openSzervizModal('${a.rendszam}')" class="flex-1 bg-blue-600/80 hover:bg-blue-500 text-white text-xs py-1.5 rounded transition">🛠️ Szerviz</button><button onclick="openEditModal('${a.rendszam}')" class="flex-1 bg-amber-600/80 hover:bg-amber-500 text-white text-xs py-1.5 rounded transition">✏️ Módosít</button><button onclick="deleteAutoAction('${a.rendszam}')" class="flex-1 bg-red-600/80 hover:bg-red-500 text-white text-xs py-1.5 rounded transition">🗑️</button></div>` : ''}</div>`).join(''); const rendszamSelect = document.getElementById('utRendszam'); if (rendszamSelect) { const elerhetoAutok = autok.filter(a => a.elerhetoAFormDatumon); const jelenlegiKivalasztott = rendszamSelect.value; let opciok = '<option value="">-- Válassz autót --</option>'; if (elerhetoAutok.length === 0) opciok = '<option value="">-- Nincs szabad autó --</option>'; else opciok += elerhetoAutok.map(a => `<option value="${a.rendszam}">${a.rendszam} (${a.tipus})</option>`).join(''); if (rendszamSelect.innerHTML !== opciok) { rendszamSelect.innerHTML = opciok; if (elerhetoAutok.some(a => a.rendszam === jelenlegiKivalasztott)) rendszamSelect.value = jelenlegiKivalasztott; } } } catch(e) {} }
async function loadUtak() { const token = window.AppState.token; const currentUser = window.AppState.user; if (!token || !currentUser) return; const szuro = document.getElementById('kerelmekSzuro'); const kivalasztottHonap = szuro ? szuro.value : ''; try { const utak = await API.fetchUtak(token, currentUser.role === 'ADMIN', kivalasztottHonap); if (!Array.isArray(utak)) return; if(utak.length === 0) { document.getElementById('utList').innerHTML = '<tr><td colspan="7" class="py-4 text-center text-slate-500 text-sm">Nincs találat.</td></tr>'; return; } document.getElementById('utList').innerHTML = utak.map(u => { let gombHTML = '-'; if(currentUser.role === 'ADMIN' && u.status === 'BEERKEZO') { gombHTML = `<div class="flex gap-2"><button onclick="biralUtFizikai(${u.id}, 'JOVAHAGYOTT')" class="bg-emerald-600 hover:bg-emerald-500 text-white px-2 py-1 rounded text-xs">✔</button><button onclick="biralUtFizikai(${u.id}, 'ELUTASITOTT')" class="bg-red-600 hover:bg-red-500 text-white px-2 py-1 rounded text-xs">✖</button></div>`; } else if (currentUser.role === 'USER' && u.status === 'JOVAHAGYOTT') { gombHTML = `<button onclick="openLezarModal(${u.id}, '${u.auto_rendszam}')" class="bg-blue-600 hover:bg-blue-500 text-white px-3 py-1 rounded text-xs font-bold w-full shadow-lg shadow-blue-500/20">⛽ Lezárás</button>`; } let statusColor = 'bg-amber-900/50 text-amber-400'; if(u.status === 'JOVAHAGYOTT') statusColor = 'bg-emerald-900/50 text-emerald-400 border-emerald-500/30 border'; if(u.status === 'ELUTASITOTT') statusColor = 'bg-red-900/50 text-red-400'; if(u.status === 'TELJESITVE') statusColor = 'bg-blue-900/50 text-blue-300'; return `<tr><td class="py-3 text-slate-400">#${u.id}</td><td class="py-3 text-blue-400 font-mono text-xs font-semibold">${u.honap_ev}</td><td class="py-3 font-bold text-white">${u.sofor_nev}</td><td class="py-3"><span class="bg-slate-900 px-2 py-1 rounded text-xs">${u.auto_rendszam}</span></td><td class="py-3 text-slate-300">${u.indulas} ➔ ${u.erkezes} (${u.tavolsag} km)<br/><span class="text-[10px] text-slate-500">Költség: ${u.koltseg} RON | Fogy.: ${u.fogyasztas}L</span></td><td class="py-3"><span class="text-xs px-2 py-1 rounded font-bold ${statusColor}">${u.status}</span></td><td class="py-3">${gombHTML}</td></tr>`; }).join(''); } catch(e) {} }
document.addEventListener('click', (e) => { if (!e.target.closest('.relative')) { document.getElementById('indulasList')?.classList.add('hidden'); document.getElementById('erkezesList')?.classList.add('hidden'); }});